#!/bin/bash
# Shell script that will import traces into Trace Compass and output their critical paths in a string format for comparison

tracecompassPath="/home/henry/trace-compass"
scriptPath="/home/henry/.tracecompass/DataFiltering/EaseScripts/collectAndVectorize.js"
path1="/home/henry/.tracecompass/DataFiltering/SampleTraces/wget"
path2="/kernel "
path=""
space=" "


numTraces=500
#runSize=10
#let numRuns=$numTraces % $runSize
#for ((a=1; a<= numRuns; a++)); do

#for ((i=1; i<=runSize; i++)); do
for ((i=1; i<=numTraces; i++)); do
   	path=${path}${path1}${i}${path2}${space}
done
cd $tracecompassPath
./tracecompass --cli --open $path --script $scriptPath
#done
pkill tracecompass
