#!/bin/bash
# Run wget mulitple times while being traced by lttng. Traces will be saved into a directory named Trace which will share the same path as this script.
#the website to run wget on can be specified in $target
#The name of the wget output should be specified in $wgetFile so it can be deleted
#To change output location, change $path to the path of your desired output location
#To change the output name, change $name

target="brocku.ca"
path=$(pwd)
name="wget"
wgetFile=index.html

for i in {1..3}
do
	
	lttng create $name$i --output=$path/Traces/$name$i
	lttng enable-event -k --syscall --all
	lttng add-context --kernel --type=tid
	lttng enable-event -k sched_switch,sched_waking,sched_pi_setprio,sched_process_fork,sched_process_exit,sched_process_free,sched_wakeup,irq_softirq_entry,irq_softirq_raise,irq_softirq_exit,irq_handler_entry,irq_handler_exit,lttng_statedump_process_state,lttng_statedump_start,lttng_statedump_end,lttng_statedump_network_interface,lttng_statedump_block_device,block_rq_complete,block_rq_insert,block_rq_issue,block_bio_frontmerge,sched_migrate,sched_migrate_task,power_cpu_frequency,net_dev_queue,netif_receive_skb,net_if_receive_skb,timer_hrtimer_start,timer_hrtimer_cancel,timer_hrtimer_expire_entry,timer_hrtimer_expire_exit
	lttng start
	wget ${target}
	lttng destroy
	rm -r $wgetFile
done
