#!/bin/bash
#  Shell script that will import traces into Trace Compass and output the syscalls that belong to their critical paths

tracecompassPath="/home/henry/trace-compass"
scriptPath="/home/henry/.tracecompass/DataFiltering/EaseScripts/compareSyscallsCLI.js"
path1="/home/henry/.tracecompass/DataFiltering/SampleTraces/wget"
path2="/kernel "
path=""

numTraces=10

for i in {1..$numTraces}
do

   path=${path}$path1$i$path2
 
done
cd $tracecompassPath
./tracecompass --cli --open $path   --script $scriptPath


